### ISSUE TITLE
dump: AttributeError: 'file' object has no attribute 'path'

### ISSUE THREAD

**Issue by jayvdb** [ssato/python-anyconfig#102]
When running anyconfig 0.9.8 with the tests for backend cbor, on Python 2.7

```console
[    7s] ======================================================================
[    7s] ERROR: test_32_dump_to_stream (tests.cbor.Test_20)
[    7s] ----------------------------------------------------------------------
[    7s] Traceback (most recent call last):
[    7s]   File "/home/abuild/rpmbuild/BUILD/python-anyconfig-cbor-backend-RELEASE_0.0.3/tests/common.py", line 279, in test_32_dump_to_stream
[    7s]     self.psr.dump(self.cnf, strm)
[    7s]   File "/usr/lib/python2.7/site-packages/anyconfig/backend/base.py", line 378, in dump
[    7s]     ensure_outdir_exists(ioi.path)
[    7s] AttributeError: 'file' object has no attribute 'path'
```

Same thing when running tests for ion on Python 3.7

```console
[   26s] ======================================================================
[   26s] ERROR: test_30_dump (tests.10_backend.Test_20)
[   26s] ----------------------------------------------------------------------
[   26s] Traceback (most recent call last):
[   26s]   File "/home/abuild/rpmbuild/BUILD/python-anyconfig-ion-backend-RELEASE_0.0.2/tests/common.py", line 271, in test_30_dump
[   26s]     self.psr.dump(self.cnf, self.cnf_path)
[   26s]   File "/usr/lib/python3.7/site-packages/anyconfig/backend/base.py", line 378, in dump
[   26s]     ensure_outdir_exists(ioi.path)
[   26s] AttributeError: 'str' object has no attribute 'path'
```

pyjavaproperties and bson backends have similar problems.

**Comment by ssato** [comment]
I believe that this bugs exist in the following plugins were resolved in the latest releases.

- python-anyconfig-bson-backend
- python-anyconfig-cbor-backend
- python-anyconfig-cbor2-backend
- python-anyconfig-configobj-backend
- python-anyconfig-ion-backend
- python-anyconfig-msgpack-backend
