### ISSUE TITLE
Try to empty data with yaml parser causes an errror

### ISSUE THREAD

**Issue by ssato** [ssato/python-anyconfig#68]
```console
ssato@x1carbon% anyconfig_cli /dev/null -vv -I yaml
Using config parser: <class 'anyconfig.backend.yaml.Parser'> [yaml]
Loading: /dev/null
Traceback (most recent call last):
  File "/usr/bin/anyconfig_cli", line 9, in <module>
    load_entry_point('anyconfig==0.9.0', 'console_scripts', 'anyconfig_cli')()
  File "/usr/lib/python2.7/site-packages/anyconfig/cli.py", line 358, in main
    diff = _load_diff(args, options)
  File "/usr/lib/python2.7/site-packages/anyconfig/cli.py", line 337, in _load_diff
    ac_schema=options.schema)
  File "/usr/lib/python2.7/site-packages/anyconfig/api.py", line 381, in load
    **options)
  File "/usr/lib/python2.7/site-packages/anyconfig/api.py", line 337, in multi_load
    ac_template=ac_template, ac_context=cnf, **opts)
  File "/usr/lib/python2.7/site-packages/anyconfig/api.py", line 257, in single_load
    cnf = psr.load(path_or_stream, **options)
  File "/usr/lib/python2.7/site-packages/anyconfig/backend/base.py", line 285, in load
    cnf = self.load_from_path(path_or_stream, container, **options)
  File "/usr/lib/python2.7/site-packages/anyconfig/backend/base.py", line 419, in load_from_path
    return self.load_from_stream(self.ropen(filepath), container, **kwargs)
  File "/usr/lib/python2.7/site-packages/anyconfig/backend/base.py", line 70, in wrapper
    return func(*args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/anyconfig/backend/yaml.py", line 119, in _yml_load
    return container(_yml_fnc("load", stream, **kwargs))
TypeError: 'NoneType' object is not iterable
ssato@x1carbon%
```

**Comment by ssato** [comment]
I thing it was resovled by the commtis 43bd766 and 5569c2c
